name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  FormatCheckWithUnitTest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: code formatting
        run: mvn spotless:check
      - name: Run test
        run: mvn test
  TerraformPlan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./provisioning/nonprod/dev
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5
      - name: Terraform Init
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.KBY_NP_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KBY_NP_AWS_SECRET }}
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.KBY_NP_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KBY_NP_AWS_SECRET }}
        run: |
          terraform plan -input=false
